# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 445)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btPhoto = QtWidgets.QPushButton(Form)
        self.btPhoto.setGeometry(QtCore.QRect(480, 310, 81, 71))
        self.btPhoto.setAutoFillBackground(False)
        self.btPhoto.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/images/photo.jpg);")
        self.btPhoto.setText("")
        self.btPhoto.setAutoRepeat(False)
        self.btPhoto.setObjectName("btPhoto")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 390, 551, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.btExit = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btExit.sizePolicy().hasHeightForWidth())
        self.btExit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btExit.setFont(font)
        self.btExit.setAutoFillBackground(True)
        self.btExit.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.btExit.setObjectName("btExit")
        self.horizontalLayout.addWidget(self.btExit)
        self.lbTitle = QtWidgets.QLabel(Form)
        self.lbTitle.setGeometry(QtCore.QRect(10, 10, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbTitle.setFont(font)
        self.lbTitle.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.lbTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTitle.setObjectName("lbTitle")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 81, 61))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/photo.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lbCamera = QtWidgets.QLabel(Form)
        self.lbCamera.setGeometry(QtCore.QRect(100, 50, 371, 331))
        self.lbCamera.setObjectName("lbCamera")

        self.retranslateUi(Form)
        self.pushButton_2.pressed.connect(Form.test) # type: ignore
        self.btExit.clicked.connect(Form.exit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton_2, self.btExit)
        Form.setTabOrder(self.btExit, self.btPhoto)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Photo Booth"))
        self.pushButton_2.setText(_translate("Form", "Take picture"))
        self.btExit.setText(_translate("Form", "Exit"))
        self.lbTitle.setText(_translate("Form", "Photo Booth"))
        self.lbCamera.setText(_translate("Form", "TextLabel"))

